name: Build package

on:
  push:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -P github -B -ntp test verify deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
